#! /bin/bash

if test -f merged-records.csv ; then
	cp merged-records.csv ../inventory-backups/merged-records-old.csv
	rm merged-records.csv
fi
OutFileName="merged-records.csv"
i=0
for filename in ./*.csv; do
        if [ "$filename" != "$OutFileName" ] ; then
                if [[ $i -eq 0 ]] ; then
                        head -1 "$filename" > "$OutFileName"
                fi
                tail -n +2 "$filename" >> "$OutFileName"
                ((i++))
        fi
done