#! /bin/bash
OutFileName="merged-records.csv"
SaveAddress="../wpallimport/files/merged-records.csv"
i=0
if test -f "$SaveAddress" ; then
	if test -f ../inventory-backups/merged-records-old.csv ; then
		rm ../inventory-backups/merged-records-old.csv
	fi
	cp "$SaveAddress" ../inventory-backups/merged-records-old.csv
	rm "$SaveAddress"
fi
for filename in ./*.csv; do
        if [ "$filename" != "$OutFileName" ] ; then
                if [[ $i -eq 0 ]] ; then
                        head -1 "$filename" > "$OutFileName"
                fi
                tail -n +2 "$filename" >> "$OutFileName"
                ((i++))
        fi
done
if test -f "$SaveAddress" ; then
	rm "$SaveAddress"
	cp "$OutFileName" "$SaveAddress"
fi
